# Pin assignments
# clock
set_property PACKAGE_PIN E18 [get_ports CLKOSC]

# FIXED_SIGIN PORT -----------------------------------------------------
set_property PACKAGE_PIN V26 [get_ports {FIXED_SIGIN_U[0]}]
set_property PACKAGE_PIN V23 [get_ports {FIXED_SIGIN_U[1]}]
set_property PACKAGE_PIN W25 [get_ports {FIXED_SIGIN_U[2]}]
set_property PACKAGE_PIN Y26 [get_ports {FIXED_SIGIN_U[3]}]
set_property PACKAGE_PIN Y23 [get_ports {FIXED_SIGIN_U[4]}]
set_property PACKAGE_PIN AA24 [get_ports {FIXED_SIGIN_U[5]}]
set_property PACKAGE_PIN AB26 [get_ports {FIXED_SIGIN_U[6]}]
set_property PACKAGE_PIN AB24 [get_ports {FIXED_SIGIN_U[7]}]
set_property PACKAGE_PIN AE26 [get_ports {FIXED_SIGIN_U[8]}]
set_property PACKAGE_PIN AF25 [get_ports {FIXED_SIGIN_U[9]}]
set_property PACKAGE_PIN AD25 [get_ports {FIXED_SIGIN_U[10]}]
set_property PACKAGE_PIN AD24 [get_ports {FIXED_SIGIN_U[11]}]
set_property PACKAGE_PIN AF23 [get_ports {FIXED_SIGIN_U[12]}]
set_property PACKAGE_PIN AD23 [get_ports {FIXED_SIGIN_U[13]}]
set_property PACKAGE_PIN AE22 [get_ports {FIXED_SIGIN_U[14]}]
set_property PACKAGE_PIN AE21 [get_ports {FIXED_SIGIN_U[15]}]
set_property PACKAGE_PIN V24 [get_ports {FIXED_SIGIN_U[16]}]
set_property PACKAGE_PIN W26 [get_ports {FIXED_SIGIN_U[17]}]
set_property PACKAGE_PIN W24 [get_ports {FIXED_SIGIN_U[18]}]
set_property PACKAGE_PIN Y25 [get_ports {FIXED_SIGIN_U[19]}]
set_property PACKAGE_PIN AA25 [get_ports {FIXED_SIGIN_U[20]}]
set_property PACKAGE_PIN AA23 [get_ports {FIXED_SIGIN_U[21]}]
set_property PACKAGE_PIN AB25 [get_ports {FIXED_SIGIN_U[22]}]
set_property PACKAGE_PIN AC26 [get_ports {FIXED_SIGIN_U[23]}]
set_property PACKAGE_PIN AD26 [get_ports {FIXED_SIGIN_U[24]}]
set_property PACKAGE_PIN AE25 [get_ports {FIXED_SIGIN_U[25]}]
set_property PACKAGE_PIN AF24 [get_ports {FIXED_SIGIN_U[26]}]
set_property PACKAGE_PIN AC24 [get_ports {FIXED_SIGIN_U[27]}]
set_property PACKAGE_PIN AE23 [get_ports {FIXED_SIGIN_U[28]}]
set_property PACKAGE_PIN AF22 [get_ports {FIXED_SIGIN_U[29]}]
set_property PACKAGE_PIN AC22 [get_ports {FIXED_SIGIN_U[30]}]
set_property PACKAGE_PIN AD21 [get_ports {FIXED_SIGIN_U[31]}]

set_property PACKAGE_PIN N22 [get_ports {FIXED_SIGIN_D[0]}]
set_property PACKAGE_PIN P23 [get_ports {FIXED_SIGIN_D[1]}]
set_property PACKAGE_PIN R22 [get_ports {FIXED_SIGIN_D[2]}]
set_property PACKAGE_PIN T22 [get_ports {FIXED_SIGIN_D[3]}]
set_property PACKAGE_PIN U21 [get_ports {FIXED_SIGIN_D[4]}]
set_property PACKAGE_PIN K25 [get_ports {FIXED_SIGIN_D[5]}]
set_property PACKAGE_PIN L24 [get_ports {FIXED_SIGIN_D[6]}]
set_property PACKAGE_PIN M26 [get_ports {FIXED_SIGIN_D[7]}]
set_property PACKAGE_PIN M24 [get_ports {FIXED_SIGIN_D[8]}]
set_property PACKAGE_PIN N24 [get_ports {FIXED_SIGIN_D[9]}]
set_property PACKAGE_PIN P26 [get_ports {FIXED_SIGIN_D[10]}]
set_property PACKAGE_PIN P24 [get_ports {FIXED_SIGIN_D[11]}]
set_property PACKAGE_PIN R25 [get_ports {FIXED_SIGIN_D[12]}]
set_property PACKAGE_PIN T25 [get_ports {FIXED_SIGIN_D[13]}]
set_property PACKAGE_PIN T23 [get_ports {FIXED_SIGIN_D[14]}]
set_property PACKAGE_PIN U25 [get_ports {FIXED_SIGIN_D[15]}]
set_property PACKAGE_PIN N21 [get_ports {FIXED_SIGIN_D[16]}]
set_property PACKAGE_PIN P21 [get_ports {FIXED_SIGIN_D[17]}]
set_property PACKAGE_PIN R21 [get_ports {FIXED_SIGIN_D[18]}]
set_property PACKAGE_PIN U22 [get_ports {FIXED_SIGIN_D[19]}]
set_property PACKAGE_PIN K26 [get_ports {FIXED_SIGIN_D[20]}]
set_property PACKAGE_PIN L25 [get_ports {FIXED_SIGIN_D[21]}]
set_property PACKAGE_PIN M22 [get_ports {FIXED_SIGIN_D[22]}]
set_property PACKAGE_PIN M25 [get_ports {FIXED_SIGIN_D[23]}]
set_property PACKAGE_PIN N26 [get_ports {FIXED_SIGIN_D[24]}]
set_property PACKAGE_PIN N23 [get_ports {FIXED_SIGIN_D[25]}]
set_property PACKAGE_PIN P25 [get_ports {FIXED_SIGIN_D[26]}]
set_property PACKAGE_PIN R26 [get_ports {FIXED_SIGIN_D[27]}]
set_property PACKAGE_PIN R23 [get_ports {FIXED_SIGIN_D[28]}]
set_property PACKAGE_PIN T24 [get_ports {FIXED_SIGIN_D[29]}]
set_property PACKAGE_PIN U26 [get_ports {FIXED_SIGIN_D[30]}]
set_property PACKAGE_PIN U24 [get_ports {FIXED_SIGIN_D[31]}]

# MZN connector --------------------------------------------------
# MZN up
set_property PACKAGE_PIN U7 [get_ports {MZN_SIGOUT_UP[0]}]
set_property PACKAGE_PIN V6 [get_ports {MZN_SIGOUT_UN[0]}]
set_property PACKAGE_PIN U6 [get_ports {MZN_SIGOUT_UP[1]}]
set_property PACKAGE_PIN U5 [get_ports {MZN_SIGOUT_UN[1]}]
set_property PACKAGE_PIN U2 [get_ports {MZN_SIGOUT_UP[2]}]
set_property PACKAGE_PIN U1 [get_ports {MZN_SIGOUT_UN[2]}]
set_property PACKAGE_PIN W10 [get_ports {MZN_SIGOUT_UP[3]}]
set_property PACKAGE_PIN W9 [get_ports {MZN_SIGOUT_UN[3]}]
set_property PACKAGE_PIN V9 [get_ports {MZN_SIGOUT_UP[4]}]
set_property PACKAGE_PIN W8 [get_ports {MZN_SIGOUT_UN[4]}]
set_property PACKAGE_PIN V8 [get_ports {MZN_SIGOUT_UP[5]}]
set_property PACKAGE_PIN V7 [get_ports {MZN_SIGOUT_UN[5]}]
set_property PACKAGE_PIN V4 [get_ports {MZN_SIGOUT_UP[6]}]
set_property PACKAGE_PIN W4 [get_ports {MZN_SIGOUT_UN[6]}]
set_property PACKAGE_PIN V3 [get_ports {MZN_SIGOUT_UP[7]}]
set_property PACKAGE_PIN W3 [get_ports {MZN_SIGOUT_UN[7]}]
set_property PACKAGE_PIN V2 [get_ports {MZN_SIGOUT_UP[8]}]
set_property PACKAGE_PIN V1 [get_ports {MZN_SIGOUT_UN[8]}]
set_property PACKAGE_PIN W6 [get_ports {MZN_SIGOUT_UP[9]}]
set_property PACKAGE_PIN W5 [get_ports {MZN_SIGOUT_UN[9]}]
set_property PACKAGE_PIN Y3 [get_ports {MZN_SIGOUT_UP[10]}]
set_property PACKAGE_PIN Y2 [get_ports {MZN_SIGOUT_UN[10]}]
set_property PACKAGE_PIN AA8 [get_ports {MZN_SIGOUT_UP[11]}]
set_property PACKAGE_PIN AA7 [get_ports {MZN_SIGOUT_UN[11]}]
set_property PACKAGE_PIN Y6 [get_ports {MZN_SIGOUT_UP[12]}]
set_property PACKAGE_PIN Y5 [get_ports {MZN_SIGOUT_UN[12]}]
set_property PACKAGE_PIN AA3 [get_ports {MZN_SIGOUT_UP[13]}]
set_property PACKAGE_PIN AA2 [get_ports {MZN_SIGOUT_UN[13]}]
set_property PACKAGE_PIN AE3 [get_ports {MZN_SIGOUT_UP[14]}]
set_property PACKAGE_PIN AE2 [get_ports {MZN_SIGOUT_UN[14]}]
set_property PACKAGE_PIN AE6 [get_ports {MZN_SIGOUT_UP[15]}]
set_property PACKAGE_PIN AE5 [get_ports {MZN_SIGOUT_UN[15]}]
set_property PACKAGE_PIN AA5 [get_ports {MZN_SIGOUT_UP[16]}]
set_property PACKAGE_PIN AB5 [get_ports {MZN_SIGOUT_UN[16]}]
set_property PACKAGE_PIN AA4 [get_ports {MZN_SIGOUT_UP[17]}]
set_property PACKAGE_PIN AB4 [get_ports {MZN_SIGOUT_UN[17]}]
set_property PACKAGE_PIN AC9 [get_ports {MZN_SIGOUT_UP[18]}]
set_property PACKAGE_PIN AD9 [get_ports {MZN_SIGOUT_UN[18]}]
set_property PACKAGE_PIN AC8 [get_ports {MZN_SIGOUT_UP[19]}]
set_property PACKAGE_PIN AD8 [get_ports {MZN_SIGOUT_UN[19]}]
set_property PACKAGE_PIN AB7 [get_ports {MZN_SIGOUT_UP[20]}]
set_property PACKAGE_PIN AC7 [get_ports {MZN_SIGOUT_UN[20]}]
set_property PACKAGE_PIN AB6 [get_ports {MZN_SIGOUT_UP[21]}]
set_property PACKAGE_PIN AC6 [get_ports {MZN_SIGOUT_UN[21]}]
set_property PACKAGE_PIN AC4 [get_ports {MZN_SIGOUT_UP[22]}]
set_property PACKAGE_PIN AC3 [get_ports {MZN_SIGOUT_UN[22]}]
set_property PACKAGE_PIN AB2 [get_ports {MZN_SIGOUT_UP[23]}]
set_property PACKAGE_PIN AC2 [get_ports {MZN_SIGOUT_UN[23]}]
set_property PACKAGE_PIN AB1 [get_ports {MZN_SIGOUT_UP[24]}]
set_property PACKAGE_PIN AC1 [get_ports {MZN_SIGOUT_UN[24]}]
set_property PACKAGE_PIN AD6 [get_ports {MZN_SIGOUT_UP[25]}]
set_property PACKAGE_PIN AD5 [get_ports {MZN_SIGOUT_UN[25]}]
set_property PACKAGE_PIN AD4 [get_ports {MZN_SIGOUT_UP[26]}]
set_property PACKAGE_PIN AD3 [get_ports {MZN_SIGOUT_UN[26]}]
set_property PACKAGE_PIN AD1 [get_ports {MZN_SIGOUT_UP[27]}]
set_property PACKAGE_PIN AE1 [get_ports {MZN_SIGOUT_UN[27]}]
set_property PACKAGE_PIN AF3 [get_ports {MZN_SIGOUT_UP[28]}]
set_property PACKAGE_PIN AF2 [get_ports {MZN_SIGOUT_UN[28]}]
set_property PACKAGE_PIN AF5 [get_ports {MZN_SIGOUT_UP[29]}]
set_property PACKAGE_PIN AF4 [get_ports {MZN_SIGOUT_UN[29]}]
set_property PACKAGE_PIN AE7 [get_ports {MZN_SIGOUT_UP[30]}]
set_property PACKAGE_PIN AF7 [get_ports {MZN_SIGOUT_UN[30]}]
set_property PACKAGE_PIN AE8 [get_ports {MZN_SIGOUT_UP[31]}]
set_property PACKAGE_PIN AF8 [get_ports {MZN_SIGOUT_UN[31]}]

# MZN down
set_property PACKAGE_PIN Y8 [get_ports {MZN_SIGOUT_DP[0]}]
set_property PACKAGE_PIN Y7 [get_ports {MZN_SIGOUT_DN[0]}]
set_property PACKAGE_PIN Y11 [get_ports {MZN_SIGOUT_DP[1]}]
set_property PACKAGE_PIN Y10 [get_ports {MZN_SIGOUT_DN[1]}]
set_property PACKAGE_PIN Y13 [get_ports {MZN_SIGOUT_DP[2]}]
set_property PACKAGE_PIN Y12 [get_ports {MZN_SIGOUT_DN[2]}]
set_property PACKAGE_PIN AA13 [get_ports {MZN_SIGOUT_DP[3]}]
set_property PACKAGE_PIN AA12 [get_ports {MZN_SIGOUT_DN[3]}]
set_property PACKAGE_PIN AA10 [get_ports {MZN_SIGOUT_DP[4]}]
set_property PACKAGE_PIN AB10 [get_ports {MZN_SIGOUT_DN[4]}]
set_property PACKAGE_PIN AA14 [get_ports {MZN_SIGOUT_DP[5]}]
set_property PACKAGE_PIN AA15 [get_ports {MZN_SIGOUT_DN[5]}]
set_property PACKAGE_PIN AB14 [get_ports {MZN_SIGOUT_DP[6]}]
set_property PACKAGE_PIN AB15 [get_ports {MZN_SIGOUT_DN[6]}]
set_property PACKAGE_PIN Y15 [get_ports {MZN_SIGOUT_DP[7]}]
set_property PACKAGE_PIN Y16 [get_ports {MZN_SIGOUT_DN[7]}]
set_property PACKAGE_PIN Y17 [get_ports {MZN_SIGOUT_DP[8]}]
set_property PACKAGE_PIN Y18 [get_ports {MZN_SIGOUT_DN[8]}]
set_property PACKAGE_PIN AA17 [get_ports {MZN_SIGOUT_DP[9]}]
set_property PACKAGE_PIN AA18 [get_ports {MZN_SIGOUT_DN[9]}]
set_property PACKAGE_PIN AA19 [get_ports {MZN_SIGOUT_DP[10]}]
set_property PACKAGE_PIN AA20 [get_ports {MZN_SIGOUT_DN[10]}]
set_property PACKAGE_PIN W15 [get_ports {MZN_SIGOUT_DP[11]}]
set_property PACKAGE_PIN W16 [get_ports {MZN_SIGOUT_DN[11]}]
set_property PACKAGE_PIN W18 [get_ports {MZN_SIGOUT_DP[12]}]
set_property PACKAGE_PIN W19 [get_ports {MZN_SIGOUT_DN[12]}]
set_property PACKAGE_PIN AE13 [get_ports {MZN_SIGOUT_DP[13]}]
set_property PACKAGE_PIN AF13 [get_ports {MZN_SIGOUT_DN[13]}]
set_property PACKAGE_PIN AC19 [get_ports {MZN_SIGOUT_DP[14]}]
set_property PACKAGE_PIN AD19 [get_ports {MZN_SIGOUT_DN[14]}]
set_property PACKAGE_PIN AB19 [get_ports {MZN_SIGOUT_DP[15]}]
set_property PACKAGE_PIN AB20 [get_ports {MZN_SIGOUT_DN[15]}]
set_property PACKAGE_PIN AD10 [get_ports {MZN_SIGOUT_DP[16]}]
set_property PACKAGE_PIN AE10 [get_ports {MZN_SIGOUT_DN[16]}]
set_property PACKAGE_PIN AD11 [get_ports {MZN_SIGOUT_DP[17]}]
set_property PACKAGE_PIN AE11 [get_ports {MZN_SIGOUT_DN[17]}]
set_property PACKAGE_PIN AC13 [get_ports {MZN_SIGOUT_DP[18]}]
set_property PACKAGE_PIN AD13 [get_ports {MZN_SIGOUT_DN[18]}]
set_property PACKAGE_PIN AC14 [get_ports {MZN_SIGOUT_DP[19]}]
set_property PACKAGE_PIN AD14 [get_ports {MZN_SIGOUT_DN[19]}]
set_property PACKAGE_PIN AD15 [get_ports {MZN_SIGOUT_DP[20]}]
set_property PACKAGE_PIN AE15 [get_ports {MZN_SIGOUT_DN[20]}]
set_property PACKAGE_PIN AB16 [get_ports {MZN_SIGOUT_DP[21]}]
set_property PACKAGE_PIN AC16 [get_ports {MZN_SIGOUT_DN[21]}]
set_property PACKAGE_PIN AD16 [get_ports {MZN_SIGOUT_DP[22]}]
set_property PACKAGE_PIN AE16 [get_ports {MZN_SIGOUT_DN[22]}]
set_property PACKAGE_PIN AB17 [get_ports {MZN_SIGOUT_DP[23]}]
set_property PACKAGE_PIN AC17 [get_ports {MZN_SIGOUT_DN[23]}]
set_property PACKAGE_PIN AC18 [get_ports {MZN_SIGOUT_DP[24]}]
set_property PACKAGE_PIN AD18 [get_ports {MZN_SIGOUT_DN[24]}]
set_property PACKAGE_PIN AF10 [get_ports {MZN_SIGOUT_DP[25]}]
set_property PACKAGE_PIN AF9 [get_ports {MZN_SIGOUT_DN[25]}]
set_property PACKAGE_PIN AE12 [get_ports {MZN_SIGOUT_DP[26]}]
set_property PACKAGE_PIN AF12 [get_ports {MZN_SIGOUT_DN[26]}]
set_property PACKAGE_PIN AF14 [get_ports {MZN_SIGOUT_DP[27]}]
set_property PACKAGE_PIN AF15 [get_ports {MZN_SIGOUT_DN[27]}]
set_property PACKAGE_PIN AE17 [get_ports {MZN_SIGOUT_DP[28]}]
set_property PACKAGE_PIN AF17 [get_ports {MZN_SIGOUT_DN[28]}]
set_property PACKAGE_PIN AE18 [get_ports {MZN_SIGOUT_DP[29]}]
set_property PACKAGE_PIN AF18 [get_ports {MZN_SIGOUT_DN[29]}]
set_property PACKAGE_PIN AF19 [get_ports {MZN_SIGOUT_DP[30]}]
set_property PACKAGE_PIN AF20 [get_ports {MZN_SIGOUT_DN[30]}]
set_property PACKAGE_PIN AD20 [get_ports {MZN_SIGOUT_DP[31]}]
set_property PACKAGE_PIN AE20 [get_ports {MZN_SIGOUT_DN[31]}]

# PHY ------------------------------------------------------------
set_property PACKAGE_PIN E26 [get_ports PHY_MDIO]
set_property PACKAGE_PIN D25 [get_ports PHY_MDC]
set_property PACKAGE_PIN E25 [get_ports PHY_nRST]
set_property PACKAGE_PIN F25 [get_ports PHY_HPD]

set_property PACKAGE_PIN C17 [get_ports {PHY_RXD[0]}]
set_property PACKAGE_PIN A18 [get_ports {PHY_RXD[1]}]
set_property PACKAGE_PIN C18 [get_ports {PHY_RXD[2]}]
set_property PACKAGE_PIN D18 [get_ports {PHY_RXD[3]}]
set_property PACKAGE_PIN A19 [get_ports {PHY_RXD[4]}]
set_property PACKAGE_PIN B19 [get_ports {PHY_RXD[5]}]
set_property PACKAGE_PIN C19 [get_ports {PHY_RXD[6]}]
set_property PACKAGE_PIN A20 [get_ports {PHY_RXD[7]}]
set_property PACKAGE_PIN B20 [get_ports PHY_RXDV]
set_property PACKAGE_PIN B21 [get_ports PHY_RXER]
set_property PACKAGE_PIN F22 [get_ports PHY_RX_CLK]

set_property PACKAGE_PIN C26 [get_ports {PHY_TXD[0]}]
set_property PACKAGE_PIN B26 [get_ports {PHY_TXD[1]}]
set_property PACKAGE_PIN A24 [get_ports {PHY_TXD[2]}]
set_property PACKAGE_PIN D23 [get_ports {PHY_TXD[3]}]
set_property PACKAGE_PIN A23 [get_ports {PHY_TXD[4]}]
set_property PACKAGE_PIN C22 [get_ports {PHY_TXD[5]}]
set_property PACKAGE_PIN B22 [get_ports {PHY_TXD[6]}]
set_property PACKAGE_PIN A22 [get_ports {PHY_TXD[7]}]
set_property PACKAGE_PIN C24 [get_ports PHY_TXEN]
set_property PACKAGE_PIN D26 [get_ports PHY_TXER]
set_property PACKAGE_PIN G22 [get_ports PHY_TX_CLK]

set_property PACKAGE_PIN D24 [get_ports PHY_GTX_CLK]
set_property PACKAGE_PIN C21 [get_ports PHY_CRS]
set_property PACKAGE_PIN D21 [get_ports PHY_COL]

# EEPROM ------------------------------------------------------------
set_property PACKAGE_PIN D15 [get_ports PROM_CS]
set_property PACKAGE_PIN B16 [get_ports PROM_SK]
set_property PACKAGE_PIN C16 [get_ports PROM_DI]
set_property PACKAGE_PIN D16 [get_ports PROM_DO]

# NIM IN ------------------------------------------------------------
set_property PACKAGE_PIN J24 [get_ports {NIMIN[1]}]
set_property PACKAGE_PIN J25 [get_ports {NIMIN[2]}]
set_property PACKAGE_PIN J26 [get_ports {NIMIN[3]}]
set_property PACKAGE_PIN H23 [get_ports {NIMIN[4]}]

# NIM OUT -----------------------------------------------------------
set_property PACKAGE_PIN H24 [get_ports {NIMOUT[1]}]
set_property PACKAGE_PIN H26 [get_ports {NIMOUT[2]}]
set_property PACKAGE_PIN G24 [get_ports {NIMOUT[3]}]
set_property PACKAGE_PIN G25 [get_ports {NIMOUT[4]}]

# J0 BUS ------------------------------------------------------------
#set_property PACKAGE_PIN B15 [get_ports {J0RS[1]}]
#set_property PACKAGE_PIN A15 [get_ports {J0RS[2]}]
#set_property PACKAGE_PIN C14 [get_ports {J0RS[3]}]
#set_property PACKAGE_PIN B14 [get_ports {J0RS[4]}]
#set_property PACKAGE_PIN D13 [get_ports {J0RS[5]}]
#set_property PACKAGE_PIN C13 [get_ports {J0RS[6]}]
#set_property PACKAGE_PIN A13 [get_ports {J0RS[7]}]

set_property PACKAGE_PIN E12 [get_ports {J0DC[1]}]
set_property PACKAGE_PIN E13 [get_ports {J0DC[2]}]

#set_property PACKAGE_PIN D11 [get_ports {J0DS[1]}]
#set_property PACKAGE_PIN C11 [get_ports {J0DS[2]}]
#set_property PACKAGE_PIN B11 [get_ports {J0DS[3]}]
#set_property PACKAGE_PIN D10 [get_ports {J0DS[4]}]
#set_property PACKAGE_PIN B10 [get_ports {J0DS[5]}]
#set_property PACKAGE_PIN A10 [get_ports {J0DS[6]}]
#set_property PACKAGE_PIN A9  [get_ports {J0DS[7]}]

#set_property PACKAGE_PIN B12 [get_ports {J0RC[1]}]
#set_property PACKAGE_PIN A12 [get_ports {J0RC[2]}]

# Others ------------------------------------------------------------
set_property PACKAGE_PIN C9 [get_ports {DIP[0]}]
set_property PACKAGE_PIN D9 [get_ports {DIP[1]}]
set_property PACKAGE_PIN F9 [get_ports {DIP[2]}]
set_property PACKAGE_PIN G9 [get_ports {DIP[3]}]
set_property PACKAGE_PIN H8 [get_ports {DIP[4]}]
set_property PACKAGE_PIN H9 [get_ports {DIP[5]}]
set_property PACKAGE_PIN J8 [get_ports {DIP[6]}]
set_property PACKAGE_PIN E10 [get_ports {DIP[7]}]

set_property PACKAGE_PIN A8 [get_ports {LEDOUT[0]}]
set_property PACKAGE_PIN B9 [get_ports {LEDOUT[1]}]
set_property PACKAGE_PIN D8 [get_ports {LEDOUT[2]}]
set_property PACKAGE_PIN F8 [get_ports {LEDOUT[3]}]

set_property PACKAGE_PIN A17 [get_ports PROG_B_ON]
set_property PACKAGE_PIN G26 [get_ports USER_RST_B]

# I/O standard
set_property IOSTANDARD LVCMOS33 [get_ports CLKOSC]

# input ------------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_SIGIN_U[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_SIGIN_D[*]}]
#set_property IOB true [get_ports FIXED_SIGIN_U[*]]
#set_property IOB true [get_ports FIXED_SIGIN_D[*]]

set_property IOSTANDARD LVDS [get_ports {MZN_SIGOUT_UP[*]}]
set_property IOSTANDARD LVDS [get_ports {MZN_SIGOUT_UN[*]}]
set_property IOSTANDARD LVDS [get_ports {MZN_SIGOUT_DP[*]}]
set_property IOSTANDARD LVDS [get_ports {MZN_SIGOUT_DN[*]}]

set_property DIFF_TERM true [get_ports {MZN_SIGOUT_UP[*]}]
set_property DIFF_TERM true [get_ports {MZN_SIGOUT_UN[*]}]
set_property DIFF_TERM true [get_ports {MZN_SIGOUT_DP[*]}]
set_property DIFF_TERM true [get_ports {MZN_SIGOUT_DN[*]}]

#set_property IOB true [get_ports MZN_SIGOUT_UP[*]]
#set_property IOB true [get_ports MZN_SIGOUT_UN[*]]
#set_property IOB true [get_ports MZN_SIGOUT_DP[*]]
#set_property IOB true [get_ports MZN_SIGOUT_DN[*]]
# input ------------------------------------------------------------

set_property IOSTANDARD LVCMOS33 [get_ports PHY_MDIO]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_nRST]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_HPD]

set_property IOSTANDARD LVCMOS33 [get_ports {PHY_RXD[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXDV]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXER]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RX_CLK]

set_property IOSTANDARD LVCMOS33 [get_ports {PHY_TXD[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXEN]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXER]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TX_CLK]

set_property IOSTANDARD LVCMOS33 [get_ports PHY_GTX_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_CRS]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_COL]

set_property IOSTANDARD LVCMOS33 [get_ports PROM_CS]
set_property IOSTANDARD LVCMOS33 [get_ports PROM_SK]
set_property IOSTANDARD LVCMOS33 [get_ports PROM_DI]
set_property IOSTANDARD LVCMOS33 [get_ports PROM_DO]

set_property IOSTANDARD LVCMOS33 [get_ports {DIP[*]}]
set_property PULLUP true [get_ports {DIP[7]}]
set_property PULLUP true [get_ports {DIP[6]}]
set_property PULLUP true [get_ports {DIP[5]}]
set_property PULLUP true [get_ports {DIP[4]}]
set_property PULLUP true [get_ports {DIP[3]}]
set_property PULLUP true [get_ports {DIP[2]}]
set_property PULLUP true [get_ports {DIP[1]}]
set_property PULLUP true [get_ports {DIP[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {NIMOUT[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NIMIN[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LEDOUT[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports PROG_B_ON]
set_property IOSTANDARD LVCMOS33 [get_ports USER_RST_B]

#set_property IOSTANDARD LVCMOS33 [get_ports J0RS*]
#set_property IOSTANDARD LVCMOS33 [get_ports J0DS*]
set_property IOSTANDARD LVCMOS33 [get_ports J0DC*]
#set_property IOSTANDARD LVCMOS33 [get_ports J0RC*]


